config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :characters

      resources :actors

      resources :directors

      resources :movies
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "movies#index"
  resources :characters
  resources :actors
  resources :directors
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actor.rb
class Actor < ApplicationRecord
  # Direct associations

  has_many   :characters,
             dependent: :destroy

  # Indirect associations

  has_many   :filmography,
             through: :characters,
             source: :movie

  # Validations

  validates :name, presence: true

  # Scopes

  def to_s
    name
  end
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: %i[show edit update destroy]

  def index
    @q = Actor.ransack(params[:q])
    @actors = @q.result(distinct: true).includes(:characters,
                                                 :filmography).page(params[:page]).per(10)
  end

  def show
    @character = Character.new
  end

  def new
    @actor = Actor.new
  end

  def edit; end

  def create
    @actor = Actor.new(actor_params)

    if @actor.save
      redirect_to @actor, notice: "Actor was successfully created."
    else
      render :new
    end
  end

  def update
    if @actor.update(actor_params)
      redirect_to @actor, notice: "Actor was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @actor.destroy
    redirect_to actors_url, notice: "Actor was successfully destroyed."
  end

  private

  def set_actor
    @actor = Actor.find(params[:id])
  end

  def actor_params
    params.require(:actor).permit(:name, :dob)
  end
end

app/controllers/api/v1/actors_controller.rb
class Api::V1::ActorsController < Api::V1::GraphitiController
  def index
    actors = ActorResource.all(params)
    respond_with(actors)
  end

  def show
    actor = ActorResource.find(params)
    respond_with(actor)
  end

  def create
    actor = ActorResource.build(params)

    if actor.save
      render jsonapi: actor, status: :created
    else
      render jsonapi_errors: actor
    end
  end

  def update
    actor = ActorResource.find(params)

    if actor.update_attributes
      render jsonapi: actor
    else
      render jsonapi_errors: actor
    end
  end

  def destroy
    actor = ActorResource.find(params)

    if actor.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: actor
    end
  end
end

app/views/actors/_actor_characters.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Characters

    <a data-toggle="collapse" href="#actor_characters_new_form">
      Add character
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @actor.characters.each do |character| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to character.id, character_path(character) %>

        <%= link_to character, method: :delete, data: { confirm: "Do you really want to delete this character" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="actor_characters_new_form">
        <%= render partial: "actors/actor_characters_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/actors/_actor_characters_new_form.html.erb
<%= form_with(model: @character, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :movie_id %>

    <%= f.collection_select :movie_id, Movie.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :actor_id, value: @actor.id %>

  <div class="form-group">
    <%= f.label :name %>

    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit "Create character", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/actors/_actor_filmography.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Filmography
  </div>

  <ul class="list-group list-group-flush">
    <% @actor.filmography.each do |movie| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <a href="/movies/<%= movie.id %>">
          <%= movie %>
        </a>

      </li>
    <% end %>

  </ul>
</div>

app/views/actors/_actors_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "actors_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :dob, "Dob" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='dobgteqPicker' data-target-input="nearest">
          <%= f.text_field :dob_gteq, :class => "form-control datetimepicker-input", :placeholder => "Dob greater than or equal to", :data => {:target => '#dobgteqPicker'} %>
          <div class="input-group-append" data-target='#dobgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='doblteqPicker' data-target-input="nearest">
          <%= f.text_field :dob_lteq, :class => "form-control datetimepicker-input", :placeholder => "Dob less than or equal to", :data => {:target => '#doblteqPicker'} %>
          <div class="input-group-append" data-target='#doblteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#dobgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#doblteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#dobgteqPicker').on("dp.change", function (e) {
              $('#doblteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#doblteqPicker').on("dp.change", function (e) {
              $('#dobgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :created_at, "Movie Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='filmographygteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :filmography_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Movie Created at greater than or equal to", :data => {:target => '#filmographygteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#filmographygteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='filmographylteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :filmography_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Movie Created at less than or equal to", :data => {:target => '#filmographylteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#filmographylteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#filmographygteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#filmographylteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#filmographygteqcreated_atPicker').on("dp.change", function (e) {
              $('#filmographylteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#filmographylteqcreated_atPicker').on("dp.change", function (e) {
              $('#filmographygteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/actors" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#actors_filters">
  Show filters
</a>

app/views/actors/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Actor #<%= actor.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= actor.name %></dd>

      <dt>Dob</dt>
      <dd><%= actor.dob %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back actor, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_actor_url(actor), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to actor, method: :delete, data: { confirm: "Do you really want to delete this actor?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(actor.updated_at) %> ago
  </div>
</div>

app/views/actors/_form.html.erb
<% was_validated = actor.errors.any? %>

<%= form_with(model: actor, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = actor.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% actor.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% dob_class = "form-control" %>
    <% dob_was_invalid = actor.errors.include?(:dob) %>

    <% if was_validated %>
      <% if dob_was_invalid %>
        <% dob_class << " is-invalid" %>
      <% else %>
        <% dob_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :dob %>
    <%= f.datetime_select :dob, class: dob_class, placeholder: "Enter dob" %>
    <% if dob_was_invalid %>
      <% actor.errors.full_messages_for(:dob).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/actors/_list_item.html.erb
<%= link_to actor, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= actor %>
    <small class="text-muted">
      <%= time_ago_in_words(actor.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/actors/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Actor #<%= @actor.id %>
      </h2>

      <div class="card-body">
        <%= render "form", actor: @actor %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/actors/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Actors

      <%= link_to new_actor_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "actors/actors_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Actors

        <%= link_to new_actor_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @actors, partial: "list_item", as: :actor %>
      </div>
    </div>
  </div>
</div>

app/views/actors/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Actor
      </h2>

      <div class="card-body">
        <%= render "form", actor: @actor %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/actors/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @actor, partial: "card", as: :actor %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "actors/actor_characters" %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "actors/actor_filmography" %>
  </div>
</div>