config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :characters

      resources :actors

      resources :directors

      resources :movies
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "movies#index"
  resources :characters
  resources :actors
  resources :directors
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/director.rb
class Director < ApplicationRecord
  # Direct associations

  has_many   :filmography,
             class_name: "Movie",
             dependent: :destroy

  # Indirect associations

  # Validations

  validates :name, presence: true

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/directors_controller.rb
class Api::V1::DirectorsController < Api::V1::GraphitiController
  def index
    directors = DirectorResource.all(params)
    respond_with(directors)
  end

  def show
    director = DirectorResource.find(params)
    respond_with(director)
  end

  def create
    director = DirectorResource.build(params)

    if director.save
      render jsonapi: director, status: :created
    else
      render jsonapi_errors: director
    end
  end

  def update
    director = DirectorResource.find(params)

    if director.update_attributes
      render jsonapi: director
    else
      render jsonapi_errors: director
    end
  end

  def destroy
    director = DirectorResource.find(params)

    if director.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: director
    end
  end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :set_director, only: %i[show edit update destroy]

  def index
    @q = Director.ransack(params[:q])
    @directors = @q.result(distinct: true).includes(:filmography).page(params[:page]).per(10)
  end

  def show
    @movie = Movie.new
  end

  def new
    @director = Director.new
  end

  def edit; end

  def create
    @director = Director.new(director_params)

    if @director.save
      redirect_to @director, notice: "Director was successfully created."
    else
      render :new
    end
  end

  def update
    if @director.update(director_params)
      redirect_to @director, notice: "Director was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @director.destroy
    redirect_to directors_url, notice: "Director was successfully destroyed."
  end

  private

  def set_director
    @director = Director.find(params[:id])
  end

  def director_params
    params.require(:director).permit(:name, :dob)
  end
end

app/views/directors/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Director #<%= director.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= director.name %></dd>

      <dt>Dob</dt>
      <dd><%= director.dob %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back director, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_director_url(director), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to director, method: :delete, data: { confirm: "Do you really want to delete this director?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(director.updated_at) %> ago
  </div>
</div>

app/views/directors/_director_filmography.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Filmography

    <a data-toggle="collapse" href="#director_filmography_new_form">
      Add movie
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @director.filmography.each do |movie| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to movie.id, movie_path(movie) %>

        <%= link_to movie, method: :delete, data: { confirm: "Do you really want to delete this movie" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="director_filmography_new_form">
        <%= render partial: "directors/director_filmography_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/directors/_director_filmography_new_form.html.erb
<%= form_with(model: @movie, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :title %>

    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :year %>

    <%= f.text_field :year, class: "form-control" %>
  </div>

  <%= f.hidden_field :director_id, value: @director.id %>

  <%= f.submit "Create movie", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/directors/_directors_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "directors_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :dob, "Dob" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='dobgteqPicker' data-target-input="nearest">
          <%= f.text_field :dob_gteq, :class => "form-control datetimepicker-input", :placeholder => "Dob greater than or equal to", :data => {:target => '#dobgteqPicker'} %>
          <div class="input-group-append" data-target='#dobgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='doblteqPicker' data-target-input="nearest">
          <%= f.text_field :dob_lteq, :class => "form-control datetimepicker-input", :placeholder => "Dob less than or equal to", :data => {:target => '#doblteqPicker'} %>
          <div class="input-group-append" data-target='#doblteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#dobgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#doblteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#dobgteqPicker').on("dp.change", function (e) {
              $('#doblteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#doblteqPicker').on("dp.change", function (e) {
              $('#dobgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :created_at, "Movie Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='filmographygteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :filmography_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Movie Created at greater than or equal to", :data => {:target => '#filmographygteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#filmographygteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='filmographylteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :filmography_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Movie Created at less than or equal to", :data => {:target => '#filmographylteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#filmographylteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#filmographygteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#filmographylteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#filmographygteqcreated_atPicker').on("dp.change", function (e) {
              $('#filmographylteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#filmographylteqcreated_atPicker').on("dp.change", function (e) {
              $('#filmographygteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/directors" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#directors_filters">
  Show filters
</a>

app/views/directors/_form.html.erb
<% was_validated = director.errors.any? %>

<%= form_with(model: director, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = director.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% director.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% dob_class = "form-control" %>
    <% dob_was_invalid = director.errors.include?(:dob) %>

    <% if was_validated %>
      <% if dob_was_invalid %>
        <% dob_class << " is-invalid" %>
      <% else %>
        <% dob_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :dob %>
    <%= f.datetime_select :dob, class: dob_class, placeholder: "Enter dob" %>
    <% if dob_was_invalid %>
      <% director.errors.full_messages_for(:dob).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/directors/_list_item.html.erb
<%= link_to director, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= director %>
    <small class="text-muted">
      <%= time_ago_in_words(director.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/directors/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Director #<%= @director.id %>
      </h2>

      <div class="card-body">
        <%= render "form", director: @director %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/directors/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Directors

      <%= link_to new_director_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "directors/directors_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Directors

        <%= link_to new_director_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @directors, partial: "list_item", as: :director %>
      </div>
    </div>
  </div>
</div>

app/views/directors/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Director
      </h2>

      <div class="card-body">
        <%= render "form", director: @director %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/directors/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @director, partial: "card", as: :director %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "directors/director_filmography" %>
  </div>
</div>