config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :characters

      resources :actors

      resources :directors

      resources :movies
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "movies#index"
  resources :characters
  resources :actors
  resources :directors
  resources :movies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/character.rb
class Character < ApplicationRecord
  # Direct associations

  belongs_to :actor

  belongs_to :movie

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    movie.to_s
  end
end

app/controllers/api/v1/characters_controller.rb
class Api::V1::CharactersController < Api::V1::GraphitiController
  def index
    characters = CharacterResource.all(params)
    respond_with(characters)
  end

  def show
    character = CharacterResource.find(params)
    respond_with(character)
  end

  def create
    character = CharacterResource.build(params)

    if character.save
      render jsonapi: character, status: :created
    else
      render jsonapi_errors: character
    end
  end

  def update
    character = CharacterResource.find(params)

    if character.update_attributes
      render jsonapi: character
    else
      render jsonapi_errors: character
    end
  end

  def destroy
    character = CharacterResource.find(params)

    if character.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: character
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: %i[show edit update destroy]

  def index
    @q = Character.ransack(params[:q])
    @characters = @q.result(distinct: true).includes(:movie,
                                                     :actor).page(params[:page]).per(10)
  end

  def show; end

  def new
    @character = Character.new
  end

  def edit; end

  def create
    @character = Character.new(character_params)

    if @character.save
      message = "Character was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @character, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @character.update(character_params)
      redirect_to @character, notice: "Character was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @character.destroy
    message = "Character was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to characters_url, notice: message
    end
  end

  private

  def set_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character).permit(:movie_id, :actor_id, :name)
  end
end

app/views/characters/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Character #<%= character.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Movie</dt>
      <dd>
        <% if @character.movie.present? %>
          <%= link_to character.movie, character.movie %>
        <% end %>
      </dd>

      <dt>Actor</dt>
      <dd>
        <% if @character.actor.present? %>
          <%= link_to character.actor, character.actor %>
        <% end %>
      </dd>

      <dt>Name</dt>
      <dd><%= character.name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back character, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_character_url(character), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to character, method: :delete, data: { confirm: "Do you really want to delete this character?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(character.updated_at) %> ago
  </div>
</div>

app/views/characters/_characters_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "characters_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :created_at, "Movie Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='moviegteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :movie_created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Movie Created at greater than or equal to", :data => {:target => '#moviegteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#moviegteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='movielteqcreated_atPicker' data-target-input="nearest">
          <%= f.text_field :movie_created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Movie Created at less than or equal to", :data => {:target => '#movielteqcreated_atPicker'} %>
          <div class="input-group-append" data-target='#movielteqcreated_atPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#moviegteqcreated_atPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#movielteqcreated_atPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#moviegteqcreated_atPicker').on("dp.change", function (e) {
              $('#movielteqcreated_atPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#movielteqcreated_atPicker').on("dp.change", function (e) {
              $('#moviegteqcreated_atPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>

  <div class="form-group">
    <%= f.label :actor_name_cont, "Actor name contains" %>
    <%= f.text_field :actor_name_cont, :class => "form-control", :placeholder => "Actor name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/characters" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#characters_filters">
  Show filters
</a>

app/views/characters/_form.html.erb
<% was_validated = character.errors.any? %>

<%= form_with(model: character, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% movie_class = "form-control" %>
    <% movie_was_invalid = character.errors.include?(:movie) %>

    <% if was_validated %>
      <% if movie_was_invalid %>
        <% movie_class << " is-invalid" %>
      <% else %>
        <% movie_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :movie_id %>
    <%= f.collection_select :movie_id, Movie.all, :id, :to_s, {}, class: "form-control" %>
    <% if movie_was_invalid %>
      <% character.errors.full_messages_for(:movie).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% actor_class = "form-control" %>
    <% actor_was_invalid = character.errors.include?(:actor) %>

    <% if was_validated %>
      <% if actor_was_invalid %>
        <% actor_class << " is-invalid" %>
      <% else %>
        <% actor_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :actor_id %>
    <%= f.collection_select :actor_id, Actor.all, :id, :to_s, {}, class: "form-control" %>
    <% if actor_was_invalid %>
      <% character.errors.full_messages_for(:actor).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = character.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% character.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/characters/_list_item.html.erb
<%= link_to character, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= character %>
    <small class="text-muted">
      <%= time_ago_in_words(character.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/characters/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Character #<%= @character.id %>
      </h2>

      <div class="card-body">
        <%= render "form", character: @character %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/characters/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Characters

      <%= link_to new_character_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "characters/characters_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Characters

        <%= link_to new_character_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @characters, partial: "list_item", as: :character %>
      </div>
    </div>
  </div>
</div>

app/views/characters/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Character
      </h2>

      <div class="card-body">
        <%= render "form", character: @character %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/characters/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @character, partial: "card", as: :character %>
  </div>
</div>